// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "hermes-mode": string;
      "bridge-url": string;
      "auth-token": string;
      "request-timeout": number;
    };
  }
}
